nmae: publish to npm

on:
  push:
    branches: [ main ]
    
jobs:
  publish:
    runs-on: ubuntu-latest
    
    name: 'publish to npm'
    environment: npm
    steps:
      - uses: actions/checkout@master
      - name: Install and Build 
        run: |
          npm ci
          npm run build
      - name: 'Publish to the npm registry'
        uses: primer/publish@3.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        with:
          default_branch: 'main'

